use_frameworks!

target 'RemoteNotificationHandling_Example' do
  pod 'RemoteNotificationHandling', :path => '../'

  target 'RemoteNotificationHandling_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
